export enum HealthState {
  Healthy = 'Healthy',
  Sick = 'Sick',
  Dead = 'Dead',
}

export enum LifeStage {
  Egg = 'Egg',
  Baby = 'Baby',
  Toddler = 'Toddler',
  Child = 'Child',
  Adult = 'Adult',
}

export enum TamagotchiType {
  Fit = 'Fit',
  Normal = 'Normal',
  NightOwl = 'NightOwl',
  Fat = 'Fat',
  Ill = 'Ill',
  Lazy = 'Lazy',
}

export const DefaultError = `Something went wrong...`

export const DefaultNames: string[] = [
  'Gerrit',
  'Mochi Mochi',
  'Hamtaro',
  'Ichi Tachi',
  'Dorito',
  'Melkman',
  'Fristi',
  'Broekzakzand',
  'Geluks Overhemd',
  'Poep Chapchu',
  'Gootsteen Ontstopper',
  'Spartakus',
  'Jasper',
  'Japser',
  'Options Menu',
  'Ebichuchu',
  'Ditto',
  'Chipolata',
  'Oma',
  'Kech',
  'Wo',
  'Geluks Chinees',
  'Hidde',
  'Cin',
  'Amber',
  'Antonios',
  'Sebby',
  'Frank',
  'Dusk',
  'Dawn',
  'Conii Chan',
  'Kiko',
  'Wilnyan',
  'Linn',
  'Choco',
  'Evi',
  'Destroyer88',
  'Pachu',
  'Beru',
  'Bananya',
  'Muntenslikkende Vermaakmachine',
  'Murphy',
  'Roti',
  'Frillifish',
  'Pluto',
  'Lingan Guli',
  'Balorig',
  'Cheetos',
  'Flugel',
  'Henk Bosman',
  'Vliegende Trekman',
  'Hak Tua Geest',
]
